In [1]:
l = [3232,23,2323,23,23,2343,]

In [2]:
l

[3232, 23, 2323, 23, 23, 2343]

In [3]:
import numpy

In [4]:
import numpy as np

In [6]:
a = np.array(l)

In [7]:
a

array([3232,   23, 2323,   23,   23, 2343])

In [8]:
b = np.array([12, 453, 43.3, True, 'asw'])

In [10]:
print(b)

['12' '453' '43.3' 'True' 'asw']


In [12]:
l.pop()

2343

In [13]:
l

[3232, 23, 2323, 23, 23]

In [14]:
a.mean()

1327.8333333333333

In [19]:
c = np.array([12, 453, 43.3, 'a'])

In [20]:
print(c)

['12' '453' '43.3' 'a']


In [21]:
l

[3232, 23, 2323, 23, 23]

---

In [22]:
a

array([3232,   23, 2323,   23,   23, 2343])

In [23]:
a[2:]

array([2323,   23,   23, 2343])

In [24]:
a[2:4]

array([2323,   23])

In [25]:
b = a[2:4]

In [26]:
b

array([2323,   23])

In [28]:
b[:]= 111

In [29]:
b

array([111, 111])

In [30]:
a

array([3232,   23,  111,  111,   23, 2343])

In [31]:
c = a.copy()

In [32]:
c

array([3232,   23,  111,  111,   23, 2343])

In [34]:
c[1]=1234567

In [35]:
c

array([   3232, 1234567,     111,     111,      23,    2343])

In [36]:
a

array([3232,   23,  111,  111,   23, 2343])